Update patch set 2
Patch Set 2:

could you rebase this and test against manik's updated voltha-go patch:
https://gerrit.opencord.org/#/c/14767/

I manually rebased and used LOCAL_VOLTHAGO to get the vendor changes in but it seems there is a core function being called that does not exist:


# github.com/opencord/voltha-openolt-adapter/adaptercore
adaptercore/device_handler.go:1124:31: dh.coreProxy.GetMeterBand undefined (type *"github.com/opencord/voltha-openolt-adapter/vendor/github.com/opencord/voltha-go/adapters/common".CoreProxy has no field or method GetMeterBand)
adaptercore/openolt_flowmgr.go:230:3: undefined: allocID
adaptercore/openolt_flowmgr.go:230:52: not enough arguments in call to f.createTcontGemports
	have (uint32, uint32, uint32, string, uint32, uint32)
	want (uint32, uint32, uint32, string, uint32, uint32, uint32, uint32)
adaptercore/openolt_flowmgr.go:235:81: undefined: allocID
adaptercore/openolt_flowmgr.go:1434:24: invalid operation: kvstoreTpId != TpID (mismatched types uint32 and uint16)
adaptercore/openolt_flowmgr.go:1447:20: cannot use TpID (type uint16) as type uint32 in argument to f.divideAndAddFlow

Patch-set: 2
Label: Code-Review=0