Update patch set 3
Patch Set 3:

It looks like I need this commit https://gerrit.opencord.org/#/c/16229/ to go first. 
I am seeing below errors which seem to be coming in the review https://gerrit.opencord.org/#/c/16229/

Girishs-MacBook-Pro:voltha-openolt-adapter girish$ make lint
Running style check...
Style check OK
Running sanity check...
# github.com/opencord/voltha-openolt-adapter [github.com/opencord/voltha-openolt-adapter.test]
./main_test.go:95:17: cannot use kc (type *mockKafkaClient) as type kafka.Client in assignment:
	*mockKafkaClient does not implement kafka.Client (missing EnableLivenessChannel method)
./main_test.go:161:19: cannot use &mockKafkaClient literal (type *mockKafkaClient) as type kafka.Client in argument to kafka.MsgClient:
	*mockKafkaClient does not implement kafka.Client (missing EnableLivenessChannel method)
make: *** [lint-sanity] Error 2

Patch-set: 3
Label: Code-Review=0