Update patch set 5
Patch Set 5:

Can not build it due to the following errors: # github.com/opencord/voltha-openolt-adapter/adaptercore
adaptercore/openolt_flowmgr.go:1228:20: undefined: inter_container.InterAdapterDeleteGemPortMessage
adaptercore/openolt_flowmgr.go:1232:3: undefined: inter_container.InterAdapterMessageType_DELETE_GEM_PORT_REQUEST
adaptercore/openolt_flowmgr.go:1254:18: undefined: inter_container.InterAdapterDeleteTcontMessage
adaptercore/openolt_flowmgr.go:1258:3: undefined: inter_container.InterAdapterMessageType_DELETE_TCONT_REQUEST

Patch-set: 5
Reviewer: Gerrit User 1000404 <1000404@2a2bfe1b-c5c2-48ed-9ac8-16438ab24388>
Label: Code-Review=0